### ISSUE TITLE
Exception: sdppp PS side error:HTTP 422

### ISSUE THREAD

**Issue by rajaarulsingh** [zombieyang/sd-ppp#18]
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-4094' coro=<AsyncServer._handle_event_internal() done, defined at D:\Python\SDLATEST\system\python\lib\site-packages\socketio\async_server.py:608> exception=Exception('sdppp PS side error:HTTP 422')>
Traceback (most recent call last):
  File "D:\Python\SDLATEST\system\python\lib\site-packages\socketio\async_server.py", line 610, in _handle_event_internal
    r = await server._trigger_event(data[0], namespace, sid, *data[1:])
  File "D:\Python\SDLATEST\system\python\lib\site-packages\socketio\async_server.py", line 637, in _trigger_event
    ret = await handler(*args)
  File "D:\Python\SDLATEST\webui\extensions\sd-ppp\sdppp_python\apis.py", line 80, in c_get_image
    upload_name, opacity = await photoshopInstance.get_image(layer_id=id, bounds_id=bounds_id)
  File "D:\Python\SDLATEST\webui\extensions\sd-ppp\sdppp_python\photoshop_instance.py", line 59, in get_image
    raise Exception('sdppp PS side error:' + result['error'])
Exception: sdppp PS side error:HTTP 422

**Comment by rajaarulsingh** [comment]
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-1097' coro=<AsyncServer._handle_event_internal() done, defined at D:\Python\SDLATEST\system\python\lib\site-packages\socketio\async_server.py:608> exception=Exception('sdppp PS side error:No matching constructor overloading was found. Please see the docs for how to call the Jimp constructor.')>
Traceback (most recent call last):
  File "D:\Python\SDLATEST\system\python\lib\site-packages\socketio\async_server.py", line 610, in _handle_event_internal
    r = await server._trigger_event(data[0], namespace, sid, *data[1:])
  File "D:\Python\SDLATEST\system\python\lib\site-packages\socketio\async_server.py", line 637, in _trigger_event
    ret = await handler(*args)
  File "D:\Python\SDLATEST\webui\extensions\sd-ppp\sdppp_python\apis.py", line 80, in c_get_image
    upload_name, opacity = await photoshopInstance.get_image(layer_id=id, bounds_id=bounds_id)
  File "D:\Python\SDLATEST\webui\extensions\sd-ppp\sdppp_python\photoshop_instance.py", line 59, in get_image
    raise Exception('sdppp PS side error:' + result['error'])
Exception: sdppp PS side error:No matching constructor overloading was found. Please see the docs for how to call the Jimp constructor.

**Comment by zombieyang** [comment]
could you provide your version of Photoshop?

**Comment by rajaarulsingh** [comment]
24.0.1 (2023)
and now i installed 2024 
working on it

**Comment by zombieyang** [comment]
There is a key Photoshop API `imaging.getPixels` that only available in 24.4.0+. So sdppp is only available above that version till now. Maybe I can find another way to replace that API. 

And I want to know that will it be very unacceptable to upgrade to 24.4.1 from 24.0.1?

**Comment by cdmusic2019** [comment]
Same Issues, PS version: 25.0.0

**Comment by GeminiSquishGames** [comment]
I think we should stop supporting photoshop and do alternatives, but I'm guessing people love that flavor of koolaide too much to give it up since the status quo isn't erudite enough. But yeah, if you are asking for support of legacy versions, it's obvious you fly the Jolly Roger atop ye mast, matey!

**Comment by leetraman822** [comment]
> Same Issues, PS version: 25.0.0

me too,

**Comment by zombieyang** [comment]
seems like this bug in 25.0.0+ is not reported anymore.
24.4- is no longer planned because imaging API is deeply used now.
