### ISSUE TITLE
nodes issues

### ISSUE THREAD

**Issue by Aweirdkid69** [zombieyang/sd-ppp#47]
did everything as said but iam facing sm shi in here 
![image](https://github.com/user-attachments/assets/613d8254-bfcc-4211-92f6-3aa0bfe11539)
![image](https://github.com/user-attachments/assets/2b4fe58b-0968-48d4-92f6-f03159ed94bb)

**Comment by zombieyang** [comment]
There should be some error message in ComfyUI's console. Could you give me the log in there?

**Comment by Aweirdkid69** [comment]
> There should be some error message in ComfyUI's console. Could you give me the log in there?

here: 

```
      [!] 
[!] [notice] A new release of pip is available: 24.2 -> 24.3
[!] [notice] To update, run: c:\ALL\APPS\all\work\collection\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\python.exe -m pip install --upgrade pip
Traceback (most recent call last):
  File "c:\ALL\APPS\all\work\collection\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2001, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\asus tuf\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\custom_nodes\sd-ppp\__init__.py", line 55, in <module>
    from .sdppp_python.sdppp import SDPPP
  File "C:\Users\asus tuf\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\custom_nodes\sd-ppp\sdppp_python\sdppp.py", line 1, in <module>
    import socketio
ModuleNotFoundError: No module named 'socketio'
```

```
Cannot import C:\Users\asus tuf\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\custom_nodes\sd-ppp module for custom nodes: No module named 'socketio'
WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `C:\Users\asus tuf\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.
WAS Node Suite: Finished. Loaded 218 nodes successfully.
```

```
Import times for custom nodes:
   0.0 seconds: C:\Users\asus tuf\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: C:\Users\asus tuf\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\custom_nodes\chatbox_overlay.py
   0.0 seconds: C:\Users\asus tuf\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\custom_nodes\AIGODLIKE-COMFYUI-TRANSLATION
   0.0 seconds: C:\Users\asus tuf\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\custom_nodes\sdxl_prompt_styler
   0.0 seconds: C:\Users\asus tuf\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\custom_nodes\sd-dynamic-thresholding
   0.0 seconds: C:\Users\asus tuf\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\custom_nodes\ComfyUI-Logic
   0.0 seconds: C:\Users\asus tuf\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\custom_nodes\cg-use-everywhere
   0.0 seconds: C:\Users\asus tuf\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\custom_nodes\ComfyUI-Inpaint-CropAndStitch
   0.0 seconds: C:\Users\asus tuf\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\custom_nodes\comfyui-copilot
   0.0 seconds (IMPORT FAILED): C:\Users\asus tuf\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\custom_nodes\DynamicPose-ComfyUI
   0.0 seconds: C:\Users\asus tuf\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\custom_nodes\ComfyUI-Image-Saver
   0.0 seconds: C:\Users\asus tuf\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger
   0.0 seconds: C:\Users\asus tuf\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\custom_nodes\ComfyUI_experiments
   0.0 seconds: C:\Users\asus tuf\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\custom_nodes\ComfyUI-Image-Filters
   0.0 seconds (IMPORT FAILED): C:\Users\asus tuf\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\custom_nodes\ComfyUI-YoloWorld-EfficientSAM
   0.0 seconds: C:\Users\asus tuf\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
   0.0 seconds: C:\Users\asus tuf\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\custom_nodes\ComfyUI-SAI_API
   0.0 seconds: C:\Users\asus tuf\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\custom_nodes\comfyui-lama-remover
   0.0 seconds (IMPORT FAILED): C:\Users\asus tuf\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\custom_nodes\comfyui-reactor-node
   0.0 seconds: C:\Users\asus tuf\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\custom_nodes\comfyui-photoshop
   0.0 seconds: C:\Users\asus tuf\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\custom_nodes\comfyui-portrait-master
   0.0 seconds: C:\Users\asus tuf\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\custom_nodes\ComfyUI_FizzNodes
   0.0 seconds (IMPORT FAILED): C:\Users\asus tuf\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\custom_nodes\ComfyUI-resynthesizer
   0.0 seconds: C:\Users\asus tuf\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
   0.0 seconds: C:\Users\asus tuf\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\custom_nodes\ComfyUI_essentials
   0.0 seconds: C:\Users\asus tuf\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\custom_nodes\comfyui-tooling-nodes
   0.0 seconds: C:\Users\asus tuf\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\custom_nodes\comfyui-animatediff
   0.0 seconds: C:\Users\asus tuf\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\custom_nodes\comfyui-inpaint-nodes
   0.0 seconds: C:\Users\asus tuf\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\custom_nodes\comfy-image-saver
   0.0 seconds: C:\Users\asus tuf\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\custom_nodes\ComfyUI-BrushNet
   0.0 seconds: C:\Users\asus tuf\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\custom_nodes\ComfyMath
   0.0 seconds: C:\Users\asus tuf\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes
   0.0 seconds: C:\Users\asus tuf\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\custom_nodes\ComfyUI-LogicUtils
   0.0 seconds: C:\Users\asus tuf\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
   0.0 seconds: C:\Users\asus tuf\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\custom_nodes\ComfyUI-Prompt-MZ
   0.0 seconds: C:\Users\asus tuf\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\custom_nodes\ComfyUI-Chibi-Nodes
   0.0 seconds: C:\Users\asus tuf\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\custom_nodes\x-flux-comfyui
   0.0 seconds (IMPORT FAILED): C:\Users\asus tuf\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\custom_nodes\LCM_Inpaint_Outpaint_Comfy
   0.0 seconds (IMPORT FAILED): C:\Users\asus tuf\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\custom_nodes\comfyui-art-venture
   0.0 seconds: C:\Users\asus tuf\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\custom_nodes\ComfyUI_ProPainter_Nodes
   0.0 seconds: C:\Users\asus tuf\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\custom_nodes\efficiency-nodes-comfyui
   0.0 seconds: C:\Users\asus tuf\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\custom_nodes\ComfyUI-GGUF
   0.0 seconds: C:\Users\asus tuf\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: C:\Users\asus tuf\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\custom_nodes\OneButtonPrompt
   0.0 seconds: C:\Users\asus tuf\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
   0.0 seconds: C:\Users\asus tuf\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\custom_nodes\ComfyUI-LivePortraitKJ
   0.0 seconds: C:\Users\asus tuf\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
   0.0 seconds: C:\Users\asus tuf\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\custom_nodes\ComfyUI-JDCN
   0.0 seconds: C:\Users\asus tuf\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\custom_nodes\ComfyUI-Marigold
   0.0 seconds: C:\Users\asus tuf\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\custom_nodes\ComfyUI-Llama
   0.0 seconds: C:\Users\asus tuf\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\custom_nodes\ComfyUI-KJNodes
   0.0 seconds: C:\Users\asus tuf\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\custom_nodes\ComfyUI_smZNodes
   0.0 seconds: C:\Users\asus tuf\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack
   0.0 seconds: C:\Users\asus tuf\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
   0.0 seconds: C:\Users\asus tuf\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved
   0.1 seconds: C:\Users\asus tuf\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\custom_nodes\comfy_mtb
   0.1 seconds: C:\Users\asus tuf\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.1 seconds: C:\Users\asus tuf\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
   0.1 seconds: C:\Users\asus tuf\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\custom_nodes\comfyui_segment_anything
   0.1 seconds: C:\Users\asus tuf\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\custom_nodes\ComfyUI_LayerStyle
   0.1 seconds: C:\Users\asus tuf\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\custom_nodes\ComfyUI-Crystools
   0.2 seconds: C:\Users\asus tuf\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\custom_nodes\comfyui-ollama
   0.3 seconds: C:\Users\asus tuf\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\custom_nodes\ComfyUI-Gemini
   0.5 seconds: C:\Users\asus tuf\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\custom_nodes\ComfyUI-Manager
   0.6 seconds: C:\Users\asus tuf\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\custom_nodes\ComfyUI-SUPIR
   0.6 seconds: C:\Users\asus tuf\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\custom_nodes\ComfyUI-Easy-Use
   0.7 seconds: C:\Users\asus tuf\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\custom_nodes\ComfyUI-AdvancedLivePortrait
   0.7 seconds (IMPORT FAILED): C:\Users\asus tuf\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\custom_nodes\ComfyUI-3D-Pack
   0.8 seconds: C:\Users\asus tuf\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\custom_nodes\ComfyUI-Allor
   1.1 seconds (IMPORT FAILED): C:\Users\asus tuf\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\custom_nodes\Comfyui_Lama
   1.6 seconds: C:\Users\asus tuf\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\custom_nodes\was-node-suite-comfyui
   1.7 seconds: C:\Users\asus tuf\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\custom_nodes\comfyui-mixlab-nodes
   **1.7 seconds (IMPORT FAILED): C:\Users\asus tuf\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\custom_nodes\sd-ppp**
   3.4 seconds (IMPORT FAILED): C:\Users\asus tuf\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\custom_nodes\ComfyUI_Custom_Nodes_AlekPet
   5.1 seconds: C:\Users\asus tuf\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\custom_nodes\ComfyUI-ControlnetAux
```

**Comment by Aweirdkid69** [comment]
and here when i tried to do the (Try Fix) :

```

[]
[]
data_path:  C:\Users\asus tuf\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\custom_nodes\comfyui-mixlab-nodes\data
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json [DONE]
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json [DONE]
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json [DONE]
Install custom node 'SD-PPP'
Try fixing: ['https://github.com/zombieyang/sd-ppp']
Install: install script
Attempt to fixing '['https://github.com/zombieyang/sd-ppp']' is done.
After restarting ComfyUI, please refresh the browser.

Restarting... [Legacy Mode]


[START] Security scan

c:\ALL\APPS\all\work\collection\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable>pause
Press any key to continue . . . [DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-10-27 13:45:49.199022
** Platform: Windows
** Python version: 3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)]
** Python executable: c:\ALL\APPS\all\work\collection\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\python.exe
** ComfyUI Path: c:\ALL\APPS\all\work\collection\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI
** Log path: c:\ALL\APPS\all\work\collection\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\comfyui.log

#######################################################################
[ComfyUI-Manager] Starting dependency installation/(de)activation for the extension


## ComfyUI-Manager: EXECUTE => ['c:\\ALL\\APPS\\all\\work\\collection\\ComfyUI_windows_portable_nvidia\\ComfyUI_windows_portable\\python_embeded\\python.exe', 'install.py']

## Execute install/(de)activation script for 'C:\Users\asus tuf\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\custom_nodes\sd-ppp'

[ComfyUI-Manager] Startup script completed.
#######################################################################


Prestartup times for custom nodes:
   0.0 seconds: C:\Users\asus tuf\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: C:\Users\asus tuf\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\custom_nodes\ComfyUI-Marigold
   0.0 seconds: C:\Users\asus tuf\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\custom_nodes\ComfyUI-Easy-Use
   2.7 seconds: C:\Users\asus tuf\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\custom_nodes\ComfyUI-Manager

Traceback (most recent call last):
  File "c:\ALL\APPS\all\work\collection\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\main.py", line 90, in <module>
    import execution
  File "c:\ALL\APPS\all\work\collection\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 13, in <module>
    import nodes
  File "c:\ALL\APPS\all\work\collection\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\nodes.py", line 21, in <module>
    import comfy.diffusers_load
  File "c:\ALL\APPS\all\work\collection\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\comfy\diffusers_load.py", line 3, in <module>
    import comfy.sd
  File "c:\ALL\APPS\all\work\collection\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\comfy\sd.py", line 5, in <module>
    from comfy import model_management
  File "c:\ALL\APPS\all\work\collection\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\comfy\model_management.py", line 143, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
                                  ^^^^^^^^^^^^^^^^^^
  File "c:\ALL\APPS\all\work\collection\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\comfy\model_management.py", line 112, in get_torch_device
    return torch.device(torch.cuda.current_device())
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus tuf\AppData\Roaming\Python\Python312\site-packages\torch\cuda\__init__.py", line 940, in current_device
    _lazy_init()
  File "C:\Users\asus tuf\AppData\Roaming\Python\Python312\site-packages\torch\cuda\__init__.py", line 310, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

```

**Comment by zombieyang** [comment]
Consider remove socketio #10
