### ISSUE TITLE
M1 max , Error when installing this node

### ISSUE THREAD

**Issue by yiwangsimple** [zombieyang/sd-ppp#55]
[ERROR] An error occurred while retrieving information for the 'easy mochiLoader' node.
Traceback (most recent call last):
  File "/Users/weiwei/Documents/StabilityMatrix/Packages/ComfyUI/server.py", line 564, in get_object_info
    out[x] = node_info(x)
  File "/Users/weiwei/Documents/StabilityMatrix/Packages/ComfyUI/server.py", line 531, in node_info
    info['input'] = obj_class.INPUT_TYPES()
  File "/Users/weiwei/Documents/StabilityMatrix/Packages/ComfyUI/custom_nodes/ComfyUI-Easy-Use/py/easyNodes.py", line 2113, in INPUT_TYPES
    clip = folder_paths.get_filename_list("text_encoders")
  File "/Users/weiwei/Documents/StabilityMatrix/Packages/ComfyUI/folder_paths.py", line 326, in get_filename_list
    out = get_filename_list_(folder_name)
  File "/Users/weiwei/Documents/StabilityMatrix/Packages/ComfyUI/folder_paths.py", line 287, in get_filename_list_
    folders = folder_names_and_paths[folder_name]
KeyError: 'text_encoders'

**Comment by zombieyang** [comment]
seems not related to sd-ppp.
