### ISSUE TITLE
使用大概半小时后，Comfyui的服务器不响应了

### ISSUE THREAD

**Issue by luoq24** [zombieyang/sd-ppp#71]
got prompt
got prompt
got prompt
Task exception was never retrieved
future: <Task finished name='Task-14709' coro=<AsyncServer._handle_event_internal() done, defined at D:\Program_Green\stable-diffusion-webui\venv\lib\site-packages\socketio\async_server.py:610> exception=KeyError('dgVUA-plryRZtZ3gAAAN')>
Traceback (most recent call last):
  File "D:\Program_Green\stable-diffusion-webui\venv\lib\site-packages\socketio\async_server.py", line 612, in _handle_event_internal
    r = await server._trigger_event(data[0], namespace, sid, *data[1:])
  File "D:\Program_Green\stable-diffusion-webui\venv\lib\site-packages\socketio\async_server.py", line 640, in _trigger_event
    ret = await handler(*args)
  File "D:\Program_Green\ComfyUI\custom_nodes\sd-ppp\sdppp_python\apis.py", line 136, in c_flush_data
    store = sdppp.page_instances[sid].store
KeyError: 'dgVUA-plryRZtZ3gAAAN'
got prompt
Error handling request
Traceback (most recent call last):
  File "D:\Program_Green\stable-diffusion-webui\venv\lib\site-packages\aiohttp\web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
  File "D:\Program_Green\stable-diffusion-webui\venv\lib\site-packages\aiohttp\web_app.py", line 543, in _handle
    resp = await handler(request)
  File "D:\Program_Green\stable-diffusion-webui\venv\lib\site-packages\aiohttp\web_middlewares.py", line 114, in impl
    return await handler(request)
  File "D:\Program_Green\ComfyUI\server.py", line 62, in cache_control
    response: web.Response = await handler(request)
  File "D:\Program_Green\ComfyUI\server.py", line 140, in origin_only_middleware
    response = await handler(request)
  File "D:\Program_Green\ComfyUI\server.py", line 74, in cors_middleware
    response = await handler(request)
  File "D:\Program_Green\stable-diffusion-webui\venv\lib\site-packages\engineio\async_server.py", line 282, in handle_request
    r = await self._handle_connect(environ, transport,
  File "D:\Program_Green\stable-diffusion-webui\venv\lib\site-packages\engineio\async_server.py", line 473, in _handle_connect
    ret = await s.handle_get_request(environ)
  File "D:\Program_Green\stable-diffusion-webui\venv\lib\site-packages\engineio\async_socket.py", line 91, in handle_get_request
    return await getattr(self, '_upgrade_' + transport)(environ)
  File "D:\Program_Green\stable-diffusion-webui\venv\lib\site-packages\engineio\async_socket.py", line 149, in _upgrade_websocket
    return await ws(environ)
  File "D:\Program_Green\stable-diffusion-webui\venv\lib\site-packages\engineio\async_drivers\aiohttp.py", line 94, in __call__
    await self._sock.prepare(request)
  File "D:\Program_Green\stable-diffusion-webui\venv\lib\site-packages\aiohttp\web_ws.py", line 152, in prepare
    payload_writer = await super().prepare(request)
  File "D:\Program_Green\stable-diffusion-webui\venv\lib\site-packages\aiohttp\web_response.py", line 417, in prepare
    return await self._start(request)
  File "D:\Program_Green\stable-diffusion-webui\venv\lib\site-packages\aiohttp\web_response.py", line 425, in _start
    await self._write_headers()
  File "D:\Program_Green\stable-diffusion-webui\venv\lib\site-packages\aiohttp\web_response.py", line 505, in _write_headers
    await writer.write_headers(status_line, self._headers)
  File "D:\Program_Green\stable-diffusion-webui\venv\lib\site-packages\aiohttp\http_writer.py", line 130, in write_headers
    self._write(buf)
  File "D:\Program_Green\stable-diffusion-webui\venv\lib\site-packages\aiohttp\http_writer.py", line 75, in _write
    raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport
got prompt
!!! Exception during processing !!!
Task exception was never retrieved
future: <Task finished name='Task-14739' coro=<IocpProactor.accept.<locals>.accept_coro() done, defined at D:\Program Files\Python\Python310\lib\asyncio\windows_events.py:577> exception=OSError(22, '指定的网络名不再可用。', None, 64, None)>
Traceback (most recent call last):
  File "D:\Program Files\Python\Python310\lib\asyncio\windows_events.py", line 580, in accept_coro
    await future
  File "D:\Program Files\Python\Python310\lib\asyncio\windows_events.py", line 826, in _poll
    value = callback(transferred, key, ov)
  File "D:\Program Files\Python\Python310\lib\asyncio\windows_events.py", line 569, in finish_accept
    ov.getresult()
OSError: [WinError 64] 指定的网络名不再可用。
Traceback (most recent call last):
  File "D:\Program_Green\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\Program_Green\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\Program_Green\ComfyUI\execution.py", line 163, in _map_node_over_list
    process_inputs(input_data_all, 0)
  File "D:\Program_Green\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "D:\Program_Green\ComfyUI\custom_nodes\sd-ppp\sdppp_python\comfy\nodes_legacy.py", line 113, in get_image
    result = call_async_func_in_server_thread(
  File "D:\Program_Green\ComfyUI\custom_nodes\sd-ppp\sdppp_python\comfy\nodes_legacy.py", line 39, in call_async_func_in_server_thread
    raise handle['error']
  File "D:\Program_Green\ComfyUI\custom_nodes\sd-ppp\sdppp_python\comfy\nodes_legacy.py", line 28, in do_call
    handle['result'] = await coro
  File "D:\Program_Green\ComfyUI\custom_nodes\sd-ppp\sdppp_python\protocols\photoshop.py", line 15, in get_image
    result = await protocol_call(backend_instance, 's_get_image', data={
  File "D:\Program_Green\ComfyUI\custom_nodes\sd-ppp\sdppp_python\protocols\photoshop.py", line 4, in protocol_call
    result = await backend_instance.sdppp.sio.call(protocol_name, data=data, to=backend_instance.sid)
  File "D:\Program_Green\stable-diffusion-webui\venv\lib\site-packages\socketio\async_server.py", line 283, in call
    raise exceptions.TimeoutError() from None
socketio.exceptions.TimeoutError

Accept failed on a socket
socket: <asyncio.TransportSocket fd=6632, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 8188)>
Traceback (most recent call last):
  File "D:\Program Files\Python\Python310\lib\asyncio\proactor_events.py", line 825, in loop
    conn, addr = f.result()
OSError: [WinError 64] 指定的网络名不再可用。
Prompt executed in 194.60 seconds
Error handling request
Traceback (most recent call last):
  File "D:\Program_Green\stable-diffusion-webui\venv\lib\site-packages\aiohttp\web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
  File "D:\Program_Green\stable-diffusion-webui\venv\lib\site-packages\aiohttp\web_app.py", line 543, in _handle
    resp = await handler(request)
  File "D:\Program_Green\stable-diffusion-webui\venv\lib\site-packages\aiohttp\web_middlewares.py", line 114, in impl
    return await handler(request)
  File "D:\Program_Green\ComfyUI\server.py", line 62, in cache_control
    response: web.Response = await handler(request)
  File "D:\Program_Green\ComfyUI\server.py", line 140, in origin_only_middleware
    response = await handler(request)
  File "D:\Program_Green\ComfyUI\server.py", line 74, in cors_middleware
    response = await handler(request)
  File "D:\Program_Green\stable-diffusion-webui\venv\lib\site-packages\engineio\async_server.py", line 282, in handle_request
    r = await self._handle_connect(environ, transport,
  File "D:\Program_Green\stable-diffusion-webui\venv\lib\site-packages\engineio\async_server.py", line 473, in _handle_connect
    ret = await s.handle_get_request(environ)
  File "D:\Program_Green\stable-diffusion-webui\venv\lib\site-packages\engineio\async_socket.py", line 91, in handle_get_request
    return await getattr(self, '_upgrade_' + transport)(environ)
  File "D:\Program_Green\stable-diffusion-webui\venv\lib\site-packages\engineio\async_socket.py", line 149, in _upgrade_websocket
    return await ws(environ)
  File "D:\Program_Green\stable-diffusion-webui\venv\lib\site-packages\engineio\async_drivers\aiohttp.py", line 94, in __call__
    await self._sock.prepare(request)
  File "D:\Program_Green\stable-diffusion-webui\venv\lib\site-packages\aiohttp\web_ws.py", line 152, in prepare
    payload_writer = await super().prepare(request)
  File "D:\Program_Green\stable-diffusion-webui\venv\lib\site-packages\aiohttp\web_response.py", line 417, in prepare
    return await self._start(request)
  File "D:\Program_Green\stable-diffusion-webui\venv\lib\site-packages\aiohttp\web_response.py", line 425, in _start
    await self._write_headers()
  File "D:\Program_Green\stable-diffusion-webui\venv\lib\site-packages\aiohttp\web_response.py", line 505, in _write_headers
    await writer.write_headers(status_line, self._headers)
  File "D:\Program_Green\stable-diffusion-webui\venv\lib\site-packages\aiohttp\http_writer.py", line 130, in write_headers
    self._write(buf)
  File "D:\Program_Green\stable-diffusion-webui\venv\lib\site-packages\aiohttp\http_writer.py", line 75, in _write
    raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport
Task exception was never retrieved
future: <Task finished name='Task-14724' coro=<RequestHandler.start() done, defined at D:\Program_Green\stable-diffusion-webui\venv\lib\site-packages\aiohttp\web_protocol.py:481> exception=TypeError("'NoneType' object is not callable")>
Traceback (most recent call last):
  File "D:\Program_Green\stable-diffusion-webui\venv\lib\site-packages\aiohttp\web_protocol.py", line 524, in start
    request = self._request_factory(message, payload, self, writer, handler)
TypeError: 'NoneType' object is not callable
Error handling request
Traceback (most recent call last):
  File "D:\Program_Green\stable-diffusion-webui\venv\lib\site-packages\aiohttp\web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
  File "D:\Program_Green\stable-diffusion-webui\venv\lib\site-packages\aiohttp\web_app.py", line 543, in _handle
    resp = await handler(request)
  File "D:\Program_Green\stable-diffusion-webui\venv\lib\site-packages\aiohttp\web_middlewares.py", line 114, in impl
    return await handler(request)
  File "D:\Program_Green\ComfyUI\server.py", line 62, in cache_control
    response: web.Response = await handler(request)
  File "D:\Program_Green\ComfyUI\server.py", line 140, in origin_only_middleware
    response = await handler(request)
  File "D:\Program_Green\ComfyUI\server.py", line 74, in cors_middleware
    response = await handler(request)
  File "D:\Program_Green\stable-diffusion-webui\venv\lib\site-packages\engineio\async_server.py", line 282, in handle_request
    r = await self._handle_connect(environ, transport,
  File "D:\Program_Green\stable-diffusion-webui\venv\lib\site-packages\engineio\async_server.py", line 473, in _handle_connect
    ret = await s.handle_get_request(environ)
  File "D:\Program_Green\stable-diffusion-webui\venv\lib\site-packages\engineio\async_socket.py", line 91, in handle_get_request
    return await getattr(self, '_upgrade_' + transport)(environ)
  File "D:\Program_Green\stable-diffusion-webui\venv\lib\site-packages\engineio\async_socket.py", line 149, in _upgrade_websocket
    return await ws(environ)
  File "D:\Program_Green\stable-diffusion-webui\venv\lib\site-packages\engineio\async_drivers\aiohttp.py", line 94, in __call__
    await self._sock.prepare(request)
  File "D:\Program_Green\stable-diffusion-webui\venv\lib\site-packages\aiohttp\web_ws.py", line 152, in prepare
    payload_writer = await super().prepare(request)
  File "D:\Program_Green\stable-diffusion-webui\venv\lib\site-packages\aiohttp\web_response.py", line 417, in prepare
    return await self._start(request)
  File "D:\Program_Green\stable-diffusion-webui\venv\lib\site-packages\aiohttp\web_response.py", line 425, in _start
    await self._write_headers()
  File "D:\Program_Green\stable-diffusion-webui\venv\lib\site-packages\aiohttp\web_response.py", line 505, in _write_headers
    await writer.write_headers(status_line, self._headers)
  File "D:\Program_Green\stable-diffusion-webui\venv\lib\site-packages\aiohttp\http_writer.py", line 130, in write_headers
    self._write(buf)
  File "D:\Program_Green\stable-diffusion-webui\venv\lib\site-packages\aiohttp\http_writer.py", line 75, in _write
    raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport
got prompt
!!! Exception during processing !!! Photoshop is not connected
Traceback (most recent call last):
  File "D:\Program_Green\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\Program_Green\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\Program_Green\ComfyUI\execution.py", line 163, in _map_node_over_list
    process_inputs(input_data_all, 0)
  File "D:\Program_Green\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "D:\Program_Green\ComfyUI\custom_nodes\sd-ppp\sdppp_python\comfy\nodes_legacy.py", line 99, in get_image
    raise ValueError('Photoshop is not connected')
ValueError: Photoshop is not connected

功能很棒，大大的提高了作业的舒适度
但我今天遇到了好几次这个问题，触发了之后，只能重启server
猜测原因：在浏览器上取消队列中的任务。只是猜测

**Comment by wangsvip** [comment]
SD-PPP install failed: Bad Request

**Comment by luoq24** [comment]
插件更新到1.6.2后，问题得到了缓解。
不会卡死了
PS发现断开后，会自动重连

**Comment by netmonker** [comment]
无法重新链接。
[Diagnostics-1744703424.log](https://github.com/user-attachments/files/19753719/Diagnostics-1744703424.log)

![Image](https://github.com/user-attachments/assets/dbc52578-2450-452a-81a7-4e90abbe409d)
