### ISSUE TITLE
更新1.6后，区域蒙版不能用了，

### ISSUE THREAD

**Issue by xueqing0622** [zombieyang/sd-ppp#73]
更新1.6后，区域蒙版不能用了，
![image](https://github.com/user-attachments/assets/8679a86a-c17e-4b9b-a61f-066fdacca72d)

!!! Exception during processing !!! sdppp PS side error:Error: toImageDataArray.length(323072) !== toLength(273854)
Traceback (most recent call last):
  File "F:\ComfyUI\ComfyUI\execution.py", line 328, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\ComfyUI\execution.py", line 203, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\ComfyUI\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "F:\ComfyUI\ComfyUI\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\ComfyUI\custom_nodes\sd-ppp\sdppp_python\comfy\nodes.py", line 350, in action
    result = call_async_func_in_server_thread(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\ComfyUI\custom_nodes\sd-ppp\sdppp_python\comfy\nodes.py", line 120, in call_async_func_in_server_thread
    raise handle['error']
  File "F:\ComfyUI\ComfyUI\custom_nodes\sd-ppp\sdppp_python\comfy\nodes.py", line 109, in do_call
    handle['result'] = await coro
                       ^^^^^^^^^^
  File "F:\ComfyUI\ComfyUI\custom_nodes\sd-ppp\sdppp_python\protocols\photoshop.py", line 43, in get_selection
    result = await protocol_call(backend_instance, 's_get_selection', data={
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\ComfyUI\custom_nodes\sd-ppp\sdppp_python\protocols\photoshop.py", line 8, in protocol_call
    raise Exception('sdppp PS side error:' + result['error'])
Exception: sdppp PS side error:Error: toImageDataArray.length(323072) !== toLength(273854)

**Comment by xueqing0622** [comment]
![Uploading image.png…]()

**Comment by xueqing0622** [comment]
经过测试，就是activedocument的问题，点了当前的具体文档就没有问题，activedocument时不会更新了

**Comment by zombieyang** [comment]
1.6.1 fixed

**Comment by xueqing0622** [comment]
谢谢，非常好用，在控制上无敌了！
