### ISSUE TITLE
新版执行队列跟subgraph不兼容

### ISSUE THREAD

**Issue by xueqing0622** [zombieyang/sd-ppp#79]
之前的版本执行队列没有问题，新版的不行， 但是在网页执行队列没有问题。
冲突插件地址：https://github.com/vivax3794/ComfyUI-Sub-Nodes
![image](https://github.com/user-attachments/assets/bff05dd1-17eb-43ee-b8a3-6e65bfeaba24)

![image](https://github.com/user-attachments/assets/4ce1bf1b-b9f4-43e3-8c3c-16e799f06585)
错误代码为：
!!! Exception during processing !!! 'select'
Traceback (most recent call last):
  File "F:\ComfyUI\ComfyUI\execution.py", line 297, in execute
    required_inputs = _map_node_over_list(obj, input_data_all, "check_lazy_status", allow_interrupt=True)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\ComfyUI\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "F:\ComfyUI\ComfyUI\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\util_nodes.py", line 50, in check_lazy_status
    selected_index = int(kwargs['select'])
                         ~~~~~~^^^^^^^^^^
KeyError: 'select'

**Comment by xueqing0622** [comment]
同样的节点，冲subgraph拿出来，用编辑模式的执行队列没有问题
![image](https://github.com/user-attachments/assets/d0e2872a-e088-419f-89ee-58b43749d29f)

**Comment by zombieyang** [comment]
没能复现，1.7.0在测试下

**Comment by xueqing0622** [comment]
我用quadMoons-nodes的the button 实现了， 新版我也试一下
https://github.com/traugdor/ComfyUI-quadMoons-nodes

**Comment by xueqing0622** [comment]
新版太浪费空间了，果断回退。 习惯旧版把东西放一行。 新版这样功能一多就拉上拉下 太麻烦了

**Comment by xueqing0622** [comment]
看到你b站的视频了，去看一下怎么自定义，这个发明太好了。

**Comment by xueqing0622** [comment]
rgthree grounps 修改回同一行了，
![Image](https://github.com/user-attachments/assets/f2e33596-660c-4661-a4b4-6627905cd90b)

像这种#号的，怎么改回同一行呢，sdppp-custom.js只有 'PrimitiveNode' *rgthree*和那几个默认的，#号的也需要一个自定义的，
![Image](https://github.com/user-attachments/assets/561709b3-00e0-40b7-b768-17dc069720bc)

![Image](https://github.com/user-attachments/assets/0e0be5ff-0867-4c44-b739-6e4d3b0a0da6)

我仿照 *rgthree*加了一段在下面，还是没有用。
  sdppp.widgetable.add('*#*', (node) => {
        return {
            title: node.title,
            widgets: node.widgets.map((widget) => ({
                value: widget.value,
                name: '',
                outputType: widget.type || "string",
                options: widget.options,
                uiWeight: 1 // 设置较小的 uiWeight
            }))
        }
    })

**Comment by zombieyang** [comment]
那个匹配其实对应的是type属性不是name属性。所以要对应它的原始名字。

比如KSampler你就是加一条 `sdppp.widgetable.add('KSampler', ......)`

**Comment by xueqing0622** [comment]
可以了，感谢。 
有几个问题，
1 怎么让他们全局都挤在一行，而不是一个一个根据节点名字。
2 如果那个节点有几种不同的属性的widget，那这里怎么写： outputType: widget.type || "string",  
3 ps编辑面板的标题字号是否变小，请问哪里调整，太小了不好看清（眼神不好）
![Image](https://github.com/user-attachments/assets/33c808d3-bb40-4191-84ea-b2358a7303d0)

**Comment by zombieyang** [comment]
> 可以了，感谢。 有几个问题， 1 怎么让他们全局都挤在一行，而不是一个一个根据节点名字。 2 如果那个节点有几种不同的属性的widget，那这里怎么写： outputType: widget.type || "string", 3 ps编辑面板的标题字号是否变小，请问哪里调整，太小了不好看清（眼神不好） ![Image](https://github.com/user-attachments/assets/33c808d3-bb40-4191-84ea-b2358a7303d0)

给你个参考，含义我就不多解释了

1.
```
return {
  title: node.title + "_" + node.widgets.map(widget=> widget.label || widget.name || '').join('_')
}
```

2.
```
return {
// widgets是个数组，所以依次指定就行
  widgets: [
     { value: node.widgets[0].value, name: '', outputType: 'string' },
     { value: node.widgets[1].value, name: '', outputType: 'number' }
  ]
}
```

3. 标题字号暂时改不了

**Comment by xueqing0622** [comment]
非常感谢，已经帮了很多了！ 这个按钮和subgraph不兼容的问题在这个版本也解决了
